#!/usr/bin/env bash
#MISE description="Compiles for the current OS and architecture"
#MISE sources=["**/*.go", "go.mod", "go.sum"]
#MISE outputs={auto = true}

set -euxo pipefail

CLI=github.com/CallumKerson/release-bot/internal/cli
COMMIT=$(git rev-parse HEAD)
VERSION="$(git describe --tags --always)-dev+$(git rev-parse --short HEAD)"
go build -ldflags "-s -w -X $CLI.Version=$VERSION -X $CLI.Commit=$COMMIT -X $CLI.Date=$(date +%Y-%m-%dT%H:%M:%S%z)" -o . ./...
